import React from 'react';

export default [
	<p className='bold text-font-big text-uppercase'>A Nossa História </p>,
	<br/>,
	<br/>,
	<p>Você acredita que eu passei muito tempo em São Paulo? Eu me sinto até... eu não me sinto assim, vamos dizer assim, feliz em falar isso pra vocês. Mas São Paulo é uma cidade que pra mim ela é muito cruel e pra mim ela não existe. Dentro do meu coração.</p>,
	<br/>,
	<p className='bold tar'>Ela fala assim porque ela já sofreu muito naquela São Paulo. Eu tinha quarenta anos.</p>,
	<br/>,
	<p>São Paulo eu sofri tanto no ano de 79. Eu sofri. Muito aquele São Paulo. Vocês sabem quantos dias eu passei abaixo de um viaduto? Eu? Dezoito dias. </p>,
	<br/>,
	<p className='bold tar'>É. Aconteceu isso ai.</p>,
	<br/>,
	<p>Agora, por conta dessa peça aqui... a nossa vida, a nossa história... porque nós dois, nós somos primos legítimos. Nossas mãe, a minha e a dele, são irmã. Entendeu? E naquela época que a gente era jovem, o pessoal antigo – hoje ainda existe isso, mas antigamente era mais – achava que primo não podia se casar. Que disse que os filho saía doente, saía louco, saía não sei o quê.</p>,
	<p>Eu passei nove anos casada. Esse aqui foi meu primeiro namorado, não é? Ele é o meu primo legítimo. Mas quando a minha mãe observou que nós estava namorando, na outra cidade, antes do que essa, me mandou pra um sítio. Onde eu não tinha acesso à ele. E eles foi quem arrumaram um noivo pra mim. Só que eu não queria esse noivo. Eu queria ele. Eu gostava dele. Mas eles queriam esse noivo pra mim. Ele fica na cidade dele, ele se envolve com uma outra pessoa, entendeu? Inclusive casou. Quando eu soube que ele casou, aí eu disse eu também vou casar pra fazer raiva à ele também. Entendeu? </p>,
	<br/>,
	<p>[Filho mais velho diz pra mãe oferecer comida do jeito do nordeste. Amanhã é dia de feira, dia de biju. Dia de sexta feira só se toma café com biju nordestino]</p>,
	<br/>,
	<p>Aí então, foi dessa forma. Como eu ia falando a minha mãe me forçou, me tirou e me levou pra um sítio, onde eu não via ele. Eu fique mais de quase sete anos sem ver ele. Ele casou com um outra pessoa... engravidou essa outra pessoa... quando eu soube que ele casou aí eu digo eu também vou casar porque eu sabia que ele gostava de mim, mas eu vou casar pra maltratar ele. Do jeito que eu passei, ele vai passar também. E casei. E casei. Coisa que você nunca pode fazer. Pra machucar alguém. Hoje eu tenho consciência disso. Não é? Mas você sabe que às vezes a gente agir por impulso e tentar vingar, só me dei mal. Porque consegui casar com uma pessoa, ele casou e se separou. Né? Ele não conseguia mesmo gostar da menina e casou e separou. E eu fique nove anos e oito meses sem ver ele. Casei também. E fiquei sem ver ele.</p>,
	<br/>,
	<p className='tar'>– E nove anos ainda gostando dele?</p>,
	<br/>,
	<p>Nove anos gostando dele e sem querer o marido. Você já pensou? Casada sem querer o marido?</p>,
	<br/>,
	<p className='bold tar'>Aí é uma novela, viu. É uma novela muito dura.</p>,
	<br/>,
	<p>Vivendo com o marido, mas sem aceitar o marido. </p>,
	<br/>,
	<p className='bold tar'>É uma novela muito dura mesmo. </p>,
	<br/>,
	<p>Dá pra entender essa? E então foi nove anos e oito meses que eu não via ele. Quando a gente se encontrou eu fui embora com ele. Foi. Depois de quase dez anos sem se ver. E graças a Deus eu tenho meus filhos, todos maravilhosos, todos os três que Deus me deu, nenhum é doido nenhum é aleijado nem cego nem nada. Todos bem. Graças a Deus. </p>,
	<br/>,
	<p className='bold tar'>É e ela não teve filho nem nada com o outro marido. Ninguém sabe o por quê. </p>,
	<br/>,
	<p>Essa aqui ela teve quando eu ganhei ela em São Paulo... até isso! Essa menina ela nasceu em São Paulo. Ela tá aí caladinha assim ó, quietinha na dela.... </p>,
	<br/>,
	<p className='bold tar'>ela nasceu na maternidade Dom Pedro II</p>,
	<br/>,
	<p>ela nasceu no hospital Dom Pedro II. Não sei se ainda existe.</p>,
	<br/>,
	<p className='bold tar'>Existe. Ainda existe até hoje, Corinha. Esse hospital lá.</p>,
	<br/>,
	<p className='tar'>– Mas vocês foram pra São Paulo juntos?</p>,
	<br/>,
	<p>Quem? Eu fui embora pra São Paulo com ele! Fui embora... foi lá que eu sofri, só que. Presta atenção como foi.</p>,
	<br/>,
	<p className='bold tar'>Mas isso tem, vai fazer é.... trinta e pouco anos. Essa história, né?</p>,
	<br/>,
	<p>Eu fui pra São Paulo com ele, lá tava uma época ruim, que ele não conseguiu emprego. Então ele ficou em São Paulo pra conseguir emprego e eu voltei praqui pra o nordeste. Fiquei na casa dos meus pais, mas a gente marcou, ele falou – quando for dia 2 de fevereiro de setenta e nove..</p>,
	<br/>,
	<p>– Dia de Iemanjá...</p>,
	<br/>,
	<p>– dois de fevereiro você volta. Foi tudo certo. Então quando eu fui eu saí daqui de Petrolândia Velha, da outra cidade, dois de fevereiro. No dia marcado com ele. No dia que eu cheguei em São Paulo a firma transferiu ele. Ele conseguiu um emprego e a firma transferiu ele pro Rio de Janeiro.</p>,
	<br/>,
	<p className='bold tar'>Não é, rapaz?</p>,
	<br/>,
	<p>Aí a gente se desencontrou. </p>,
	<br/>,
	<p className='bold tar'> Aí foi um desencontro muito duro.</p>,
	<br/>,
	<p>Só que antes dele sair, eu falei assim pra ele, eu digo olha a minha localidade vai ser na casa da minha irmã. Eu tenho uma irmã. Eu fiquei com essa irmã e você acredita que ela ficou sem falar comigo trinta anos? Ela não queria eu com ele.</p>,
	<br/>,
	<p className='bold tar'>Ela tinha raiva, né, porque ela não queria....</p>,
	<br/>,
	<p className='tar'>– Porque é primo? Por causa disso?</p>,
	<br/>,
	<p>Não, porque eu já tinha outro marido. Ela queria eu com o outro. Entendeu? Só que eu falei pra ele, eu digo eu vou ficar na casa da minha irmã.</p>,
	<br/>,
	<p className='bold tar'>É muita novela, viu?!</p>,
	<br/>,
	<p>Só que olha só os desencontros da vida como que é. Ela sabia o dia que o carteiro ia levar carta na casa dela. Então todos os dias, ela com uma filha, todos os dias do carteiro ela arrumava algo pra mim sair com a menina – leve a menina. Leve a menina. Vai... vai até lá com ela. Vai passear, vai fazer isso, fazer aquilo. Pegar um cartão de vacina. Vai olhar se vacina a menina.  Sendo que ela sabia o horário e o dia que a carteiro chegava. E o carteiro chegava e trazia as minhas cartas. Dele.</p>,
	<br/>,
	<p className='tar'>– Nossa, parece novela mesmo. </p>,
	<br/>,
	<p className='bold tar'>Mas é... mas é uma novela. Novela.</p>,
	<br/>,
	<p>É então, eu queria, porque eu nunca tive condições, mas se eu tivesse condições eu iria fazer um livro da minha história. Aí você sabe o que é que acontecia? Ela rasgava as minhas cartas todas! E eu comigo pensando meu Deus, mas será que... – eu chamo ele de Iriano – mas será que Iriano é tão covarde que não escreve pra mim? Não sei onde é que ele tá. Fui na firma onde ele tava, me falaram que ele tinha transferido, assim – não.. ele trabalhava aqui mesmo, mas foi transferido. Aí pronto, fiquei sem endereço. Então eu ficava mas será que é tanta covardia dele assim? Mas não, eu não acredito. Aí passei três mês, passei quatro mês... no quinto mês veio uma noção assim na minha mente. Eu digo rapaz, isso é dia de terça e quinta que Carminha manda eu sair com essa menina. Será que tá acontecendo alguma coisa? Eu digo: vou jogar um “h” nela. Chego com a menina e disse Carminha, –  o nome dela é Maria do Carmo, mas chama Carminha – eu disse Carminha mulher, por acaso Iriano tá escrevendo para mim? Tu sabe se ele tá escrevendo pra mim?</p>,
	<br/>,
	<p className='bold tar'>Eu mandava carta direito pra você aí. </p>,
	<br/>,
	<p>Aí ela disse – não. Ele não tá escrevendo pra você não. Por quê? Aí eu disse será que tu não tá recebendo nenhuma correspondência minha aí não? Ela disse – não...eu não tô não. Mas se eu tivesse, ia ter o quê? Aí quando ela falou assim aí eu cai na ideia de que ela estava, né? Então eu digo, então você... eu já acabei de saber que ele está mandando as correspondências e você tá rasgando. Agora que eu vou falar pra você.... Aí eu falei assim ó, eu disse então você pode ter certeza que agora eu vou sair da tua casa. Agora. Porque eu tô aqui com você, cuidei  – porque ela ganhou outra nenê pequena – cuidei de sua dieta todinha, fiz de tudo e você saber que ele tá mandando as correspondência e você jogando fora, Carminha? Sem nem me avisar. Se você queimasse rasgasse fizesse tudo, mas pelo menos dissesse onde ele tava. – Eu nem disse e nem digo e você não vai morar com ele. </p>,
	<p>Você tá vendo esses dois braços que Deus me deu? Pois eu vou trabalhar e vou mostrar pra vocês... só se ele estiver debaixo do chão, mas se ele estiver em cima da terra eu vou encontrar ele. Vou encontrar ele. – Se depender de mim você não vai encontrar não.</p>,
	<p>Digo, pois eu vou mostrar pra você que eu encontro. Aí minha filha, eu vinha praqui pro nordeste, quando eu chagava ele já tinha vindo à minha procura. Ele ia embora, eu chegava. Quando eu chegava, que eu saia, ele vinha. Aí a família dele chegava e dizia – Ah, ela não veio aqui não. Ela já tem outra família. Ela já arrumou outra família. Sabe? – Ela já arrumou outra família.  Tudo pra falar isso, esse tipo de coisa. Ficava uma família jogando um com o outro. O pai dele e a mãe, que é minha tia – já faleceram. Que Deus faça com que ela não pene com nisso, né? –  mas me fez sofrer muito. Tanto eu quanto ele. Ele à minha procura e eu a procura dele. Mas as pessoa nos distanciavam. Não é que nem hoje que tem telefone, tem tudo né?</p>,
	<br/>,
	<p className='bold tar'>Antigamente não tinha telefone...</p>,
	<br/>,
	<p className='tar'>– Mas como vocês se acharam?!</p>,
	<br/>,
	<p>Mas olha só, como nós se encontramos. Ele vinha e não me encontrava. Eu chegava e ele já tinha ido. Entendeu? Aí foi até que um dia.. por isso que eu digo pra você que mulher tem mais experiência do que homem, né? Eu cheguei aí eu digo: eu agora eu vou para o nordeste e eu vou ficar lá. Eu quero ver se ele não vem. Ele uma hora ele vai lá, porque ele tem o pai e a mãe dele, alguma coisa. Ele vai lá. </p>,
	<br/>,
	<p className='tar'>– Em Petrolândia?</p>,
	<br/>,
	<p>Em Petrolândia. Quando eu cheguei e procurei –  ele já tem outra mulher! Ele já arrumou mulher, já tem filhos. – Então eu digo: é? Não tem nada não. Eu vou conversa com a mulher dele e os filhos dele. Se eu realmente ver que é verdade, então a gente se decide. Eu não vou escutar história de vocês não, porque eu sei que vocês são contra mim e contra ele. Ai já eles dizia que eu também tinha marido, tinha filho, tinha tudo. Era assim. Essa confusão toda... ele vinha, mas ele vinha chegava e perguntava.... meu nome é Socorro, mas ele chama de Corrinha. Sempre ele me chamou de Corrinha</p>,
	<br/>,
	<p className='bold tar'>é uma coisa é muito complicado.... é complicado demais.....</p>,
	<br/>,
	<p>aí ele dizia  – Corrinha chegou?  – Chegou não, ela já tem outro marido! Ela casou em São Paulo, não sei o quê. Tudo mentindo. Aí pronto a gente ficava assim... aí eu disse: agora eu vou pra lá, pro nordeste eu não vou sair de lá. Eu vou ficar lá. Eu quero ver se um dia ele não aparece. Aí quando eu cheguei eu esperta... cheguei, conversei com minha tia que é a mãe dele.. aí eu disse ô tia, Iriano não apareceu não? – Não minha filha, Iriano arrumou outra pessoa lá, já tem filho e tudo. Digo: é? – É não. Aí eu disse: ele não escreve não? –  Não, ele não manda notícia não. Mas aquilo.. eu olhando na cara você conhece gente de cara mentirosa, não é? Quem tá mentindo você pode olhar no olho que não segura o olhar em você de jeito nenhum.</p>,
	<br/>,
	<p className='bold tar'>É, é mesmo. </p>,
	<br/>,
	<p>Ó, o olho no olho, pra quem é um detetive.. ele conhece no olho a verdade e a mentira.</p>,
	<br/>,
	<p className='bold tar'>Pelas, pelas palavras também. Tudo.</p>,
	<br/>,
	<p>Você não segura o olhar. Gente mentiroso não segura o olhar em você. Pode você ter certeza disso. Não segura não. Aí eu cheguei e disse ô tia, ele não dá notícia não? – Dá não. Mas um “dá não” com a cabeça baixa. Isso aí tem mentira. Não vou chamar de mentirosa que é minha tia, né? Fica quieta. Eu digo ela não sabe ler, o marido não sabe. Ninguém sabe. Só quem sabe ler é a irmã dele, mais velha: eu vou na casa da irmã dele. Chega lá na casa da irmã dele não tinha ninguém, as porta tudo aberta. Esse pessoal, meio... sabe? Atrapalhado. Que não ligava, abre as porta e deixa aí...</p>,
	<br/>,
	<p className='bold tar'>Tem gente que não.. não liga não.</p>,
	<br/>,
	<p>Sim, quando eu cheguei, entrei e não achei ninguém. Eu disse ô delícia. Fui lá num baú velho que tinha lá. Não sei se vocês sabem o que é baú, uma mala antiga. Abri a mala antiga, dentro de um vidro grande assim, cheio de carta dele! Cheio de carta dele!  O baú ainda está ali na casa do pai dele.</p>,
	<br/>,
	<p className='bold tar'>Esse baú até hoje existe lá em casa. A gente guarda...</p>,
	<br/>,
	<p>Não tem carta, tem o baú. O baú era dos pais dele. E as carta era dele mandando pra família dele.</p>,
	<br/>,
	<p className='tar'>–  Mas hoje cadê essas cartas?</p>,
	<br/>,
	<p>As cartas era da mãe dele, entendeu? Não era pra mim. Era da mãe dele ele dizendo onde tava, essas coisas. E ela dizia que ele não escrevia. Aí eu peguei as cartas mais nova, a mais recente, olhei o endereço tudo direitinho</p>,
	<br/>,
	<p className='bold tar'>mais recente eu estava no Bom Jardim de Minas.</p>,
	<br/>,
	<p>cheguei na casa da minha vó – que minha avó também era contra. Era minha vó e vó dele. Ela não queria nós dois. –  Aí eu cheguei e disse: eita mãe velha! Hoje eu tive uma alegria! – Que foi? </p>,
	<p>Não vou dizer não, a senhora não. A senhora só vai saber depois. Aí ela –  o que é que tu tá armando? Digo nada. Cheguei tinha meu primo que até hoje ele mora aqui. Aí eu cheguei e disse ô Zé Valdo, me empresta aí um caderno e uma caneta? Aí ele me entregou, aí eu fiz uma carta. Agora, foi uma carta, viu. Fiz uma carta contando tudo tudo tudo. Quantos dia tava aqui já, quantos meses tava aqui esperando e se era real se ele tinha arrumado...</p>,
	<br/>,
	<p className='bold tar'>Ela era mais magra do que você. Ainda tem uma foto dela aí.</p>,
	<br/>,
	<p>Pronto, eu fui na casa dessa aqui ó! Na casa que eu achei as carta foi dessa aqui ó.</p>,
	<br/>,
	<p className='tar'>–  Nossa, isso era um casamento?</p>,
	<br/>,
	<p>Era. O casamento dessa.</p>,
	<br/>,
	<p className='tar'>–  Que linda.</p>,
	<br/>,
	<p>Olha eu, como eu era magrinha.</p>,
	<br/>,
	<p className='bold tar'>Não dá pra reconhecer bem porque ela já tem sessenta e poucos anos. </p>,
	<br/>,
	<p>Aí eu já era casada na época. </p>,
	<br/>,
	<p className='tar'>– Esse era seu marido?</p>,
	<br/>,
	<p>Não. Meu marido é falecido. O meu primeiro.</p>,
	<br/>,
	<p className='bold tar'>Mas é ela ficou viúva.</p>,
	<br/>,
	<p>Esse aí é o meu tio.</p>,
	<br/>,
	<p>– Muito legal essa foto. Muito linda. Mas e aí. Chegou a carta até você?</p>,
	<br/>,
	<p className='bold tar'>Chegou. Ela... ela mandou.</p>,
	<br/>,
	<p>Sim, que é que acontece? O que foi que aconteceu? Eu escrevi a carta como eu tô falando pra você, caprichei na carta. Querendo saber dele que ele me mandasse essa resposta. Com urgência ele mandasse a resposta. Se era real o que tavam me falando tudo.. se ele tinha mulher, se ele já tinha filho. Que me mandasse. Eu queria era saber da resposta. Porque eu tinha aqui em São Paulo e tinha uma senhora que ela tinha um filho paralítico e ela era uma portuguesa. E ela queria porque queria me levar para Portugal. Pra ajudar a cuidar desse rapaz. Ele tinha vinte e dois anos, só que ele era paraplégico da cintura pra baixo: as perna bem fininha. Isso aqui assim todo musculosinho, fortinho, mas as pernas bem sequinha. Deu paralisia quando ele era jovem pequenininho, recém nascido. Aí eu digo não, eu vou resolver um problema lá no nordeste e qualquer coisa eu venho praqui. Oxi, na carta eu falei pra ele se você é casado, se você tem família, você me resposta com urgência. Não precisa você vir. Só quero só a resposta, porque se você for casado eu tô indo pra Portugal. E eu ia. Aí quando eu falei assim... porque eu sou uma pessoa assim, mas se eu faço uma coisa, só aquele do céu mesmo me proibi. Eu sou assim.</p>,
	<br/>,
	<p className='bold tar'>Ela é.. é decidida mesmo ela.  É... é boca pesada, ela mesmo.</p>,
	<br/>,
	<p className='tar'>Mãe dá um livro. A história de mãe dá um livro. </p>,
	<br/>,
	<p>História de mãe dá um livro. Então minha filha a gente, eu cheguei eu digo e agora? Fiquei o coração bem apertado. Meu deus, será que é verdade isso? Mas se for tudo bem. A pessoa tem que levantar, tem que conseguir encarar as coisas do jeito que é, não pode ficar né, pensando em nada não, tem que encarar a realidade. Então, daí eu peguei fiquei aguardando, esperando. Eu digo e mande com urgência. Aí era só botar no correio, registrei a carta. Desde que ele tava no Rio de Janeiro e ele tava também esperando notícia minha, já tinha vindo várias vezes. Não vinha? Ele disse que foi um colega dele que falou pra ele.</p>,
	<br/>,
	<p className='bold tar'> Nessa época eu tava em Bom Jardim de Minas, assim que eu vinha eu ia chegando no serviço o..</p>,
	<p> o colega né?</p>,
	<br/>,
	<p className='bold tar'>Era. Aí falou que o guarda tinha uma carta minha. Eu falei rapaz que carta é? Eu fiquei até chega me deu uma ansiedade.</p>,
	<br/>,
	<p>Ele disse que ficou todo frio.</p>,
	<br/>,
	<p className='bold tar'>Que carta é? Aí quando eu peguei na carta, era pra mim guardar essa carta até hoje rapaz, e não guardei. Aí falava o nome... embaixo quando eu li ela aí fala o nome: Socorro. Rapaz aquilo me deu, eu digo eu vou embora agora!</p>,
	<br/>,
	<p>Você vê, ele tava na experiência, antes de vencer a experiência. Então foi que ele fez? Ele pediu na firma pra uns três a quatro dias, ele pediu – me dá oito de seis a oito dias pra mim ir no nordeste que tem um irmão doente e tudo.</p>,
	<br/>,
	<p>[Irmão mais velho chega com um prato de mandioca assada na manteiga]</p>,
	<br/>,
	<p>Então quando tudo que ele chegou que viu a carta ele pediu na firma pra dar uns 6 a 8 dias pra ele vir no nordeste e voltar eles não deram, ele tava fazendo experiência. Que foi que ele fez? Ele subiu lá e a propósito ele jogou uma táuba de cima pra baixo. Ele jogou uma táuba de cima pra baixo. Aí o cara, o encarregado – você tá loco?! Você mata alguém! Aí despediu mandou ele embora. Foi.. mandou embora. </p>,
	<br/>,
	<p className='bold tar'>Foi.</p>,
	<br/>,
	<p>Foi. Mandou embora. Aí ele rapidão passou um telegrama naquela época, um telegrama. </p>,
	<br/>,
	<p className='bold tar'>Foi, um telegrama</p>,
	<br/>,
	<p>Registrou um telegrama e no telegrama ele dizia assim – Corrinha você não me saia daí. Dia 11 eu tô chegando. Porque dia 7 a dia 8 já tava marcado pra ele receber os dias trabalhados dele. – Dia 11 eu tô chegando. Né. São Paulo pra cá 3 dias de viagem. – Dia 11 eu tô chegando.</p>,
	<br/>,
	<p className='bold tar'>Eu tava em Minas Gerais.</p>,
	<br/>,
	<p>Quando foi dia 9 ele chegou. </p>,
	<br/>,
	<p className='tar'>– E você tinha recebido já o telegrama?</p>,
	<br/>,
	<p>Já tinha recebido o telegrama. E você pensa quando chegou o telegrama, quando chegou, aí eu disse, agora vocês... reuniram eles tudinho, eita bucado de mentiroso eu disse. Vocês sabe quem vai tá aqui dia 11? Ela disse – sim. Eu digo o Iriano. Aí a irmã dele – mas Socorro como é que você foi achar ele. </p>,
	<p>Não sei, não queira saber como foi que eu achei. Que se eu achei a carta foi lá dentro do baú da casa dela. Não queria saber como eu achei mas eu falei pra vocês que eu ia encontrar ele. Se ele tivesse aqui na terra eu encontrava. Quando foi dia 9 ele chegou. Dia 9 ele chegou. 9 de fevereiro ele chegou. De setenta e nove. De setenta e nove. Quando ele chegou eu digo agora sabe o quê que a gente vai fazer? Ninguém, ninguém quer nós dois juntos, vamos se mandar. Mas também coitadinho o dinheirinho pouquinho. Vai tira pra São Paulo. – Que? Pra São Paulo. A gente foi fugiu, a gente foi pra Paulo Afonso, quando chegou em Paulo Afonso era noite</p>,
	<p className='bold tar'>era noite já.</p>,
	<br/>,
	<br/>,
	<p>aí eu a gente ficou longe assim num bar digo vamos ficar lá recantado vamos comprar passagem e vamos daquele bar a gente fica olhando o ônibus quando chega. Se o ônibus, eu digo se o ônibus chegar, você vai, você entra no ônibus, lá na frente, eu vou tá lá na frente, porque pode ser que tenha alguém aqui. E foi gente atrás da gente.</p>,
	<br/>,
	<p className='bold tar'>E foi. Foi gente mesmo.</p>,
	<br/>,
	<p>Foi gente atrás da gente. Rodou mais não conseguiu pegar. E nós foi pra Aracaju. </p>,
	<br/>,
	<p className='bold tar'>Foi mas nós armamos uma... vamos dizer, uma tragédia.</p>,
	<br/>,
	<br/>,
	<p>E a gente foi pra Aracaju, tá entendendo? </p>,
	<br/>,
	<p className='bold tar'>O dinheiro não deu pra São Paulo e nós fomos direto a Aracaju.</p>,
	<br/>,
	<p>Esse moreninho da gente</p>,
	<p className='bold tar'>nasceu lá.</p>,
	<br/>,
	<br/>,
	<p> ele nasceu em Aracaju. </p>,
	<br/>,
	<p className='bold tar'>Foi.</p>,
	<br/>,
	<p>Aí lá minha filha, lá nossa história, a nossa história foi que foi difícil lá. Você chegar no lugar sem conhecimento, sem dinheiro, uma época ruim de trabalho e ele lutava só chegava. O dinheirinho que a gente tinha só deu pra alugar um quartinho. </p>,
	<br/>,
	<p className='bold tar'>Só. Puramente.</p>,
	<br/>,
	<p>E eu sai com uma loucura tão grande que nem lençol pra gente se cobrir...sabe com o que a gente se cobria era com os meus vestido? Meu Deus e eu digo eu vou morrer de fome? Depois de criada? Eu vou nada morrer de fome nada. Eu disse peraí: peguei uma caixa de papelão escrevi cabelereira e manicure. Cortei muita cabeça de gente, fiz muito caminho de rato. Mas aprendi, tá vendo? Mas aprendi! As pessoas chegavam reclamava. Vinha reclamava! O quê?! – você derrotou me cabelo. Aí eu séria, eu digo o quê?! Você chegou com o cabelo derrotado você entrega o cabelo a todo mundo, rapaz. Eu arrumei teu cabelo, eu arrumei!  Entendeu? Aquelas que não vinha, vinha outras. E eu sei que eu fui aprendendo na cabeça dos outros e terminei aprendendo foi bom demais. Foi. E dormindo no chão e dormindo no chão. Como pensa que não? Grávida. E ai? Aí ele disse –  e aí Corrinha?  Eu digo e aí ? Se deus me deu é porque eu posso. Posso mesmo. Eu digo peraí, tem uma serralheria ali, vá lá, aquele monte de táuba que tá lá, é táuba de refugo que não querem pra jogar no lixo, vá lá, conversa com aquele homem. Fale com ele, que nós tamo necessitando. Eu tô grávida, a gente recém chegado aqui, você tá desempregado, você traz, nós compra os prego e o martelo nós faz uma cama. Bora. Pra não dormir no chão. E eu digo faça uns banquinhos também pro pessoal ir sentando. </p>,
	<br/>,
	<p className='bold tar'>Sentando.</p>,
	<br/>,
	<p>Mas minha filha, peguei tesoura emprestada e com dinheiro comprei tesoura comprei alicate. As mulher chegava – olha! Tá vendo o que você fez na minha mão? Digo: você tem o sangue ruim e a carne ruim, bora botar remédio. Não podia nem lavar roupa nem nada. E hoje eu não sei? Aprendi foi tudo e faço bem feitinha. </p>,
	<br/>,
	<p className='bold tar'>Até que ela aprendeu a fazer tudo. Mas ela não trabalha nesse ramo mais ela não.</p>,
	<br/>,
	<p>[entra a filha do filho mais velho: quer se arquiteta]</p>,
	<br/>,
	<p>E então por aí é como eu falo pra você, por isso que eu digo pra você, a coragem ela faz parte da nossa vida... por que eu falo pra você. Aí é assim, sei que aprendi e tô aqui mais meu velho cabecinha branquinha e eu também graças a Deus.</p>,
	<br/>,
	<p className='bold tar'>É já tem muitos anos isso ai, que aconteceu.</p>,
	<br/>,
	<p>E peço a Deus que Deus nos dê nossa vida até o dia que Deus quiser, mas sinceramente eu prefiro mesmo é do meu coração... eu mais meu velho nós só se aparta só quando Deus quiser. Né? </p>,
	<br/>,
	<p className='bold tar'>É. Isso aí.</p>,
	<br/>,
	<p>Porque não pode não. A gente lutou muito.</p>,
	<br/>,
	<p className='bold tar'>É, foi uma luta muito grande.</p>,
	<br/>,
	<p>Foi luta demais</p>,
	<br/>,
	<p className='bold tar'>luta grande que vai ficar na história</p>,
	<br/>,
	<p>luta contra o povo e luta contra o mundo e luta contra tudo. Mas por isso que eu digo, foi igual a uma guerra. </p>,
	<br/>,
	<p className='bold tar'>Foi isso foi uma revolução mesmo. Revolução grande mesmo.</p>,
	<br/>,
	<p>Essa irmã minha ela passou quase trinta e um anos sem falar comigo. Ela não queria falar comigo </p>,
	<br/>,
	<p className='bold tar'>mais de trinta anos de intriga. Foi fogo.</p>,
	<br/>,
	<p>Porque eu encontrei ele aí depois de muito tempo ela veio de São Paulo e chegou e falou, ela mandou uma outra irmã minha  – eu sei que Socorro tem muita raiva de mim, procura ela se ela faz uma buchada pra mim? Minha irmã falou. Digo: faço. Eu faço a buchada pra ela pra ela ver, ela vem comer na minha casa que eu disse a ela que eu ia encontrar ele.</p>,
	<br/>,
	<p className='bold tar'>É que na época a gente não tinha nada. Sem nada.</p>,
	<br/>,
	<p>E exatamente ela veio. Fiz a buchada pra ela e graças a Deus hoje está tudo bem. Ela que teve essa raiva de mim, mas não tive rancor nenhum nem raiva dela.</p>,
	<p className='bold tar'>A vida é assim, né?</p>,
	<br/>,
	<p>Me fez sofrer muito e ele também sofreu muito, ficou nervoso dentro de são Paulo. Ele ficou nervoso minha filha que ele adoeceu. Ele ia lá na casa dela. Pra você ver, eu arrumei um trabalho </p>,
	<br/>,
	<p className='bold tar'>Eu ia lá na casa dela e ainda chorei lá um bocado.</p>,
	<br/>,
	<p>antes disso, antes deu ir pra baixo de viaduto ele queria </p>,
	<br/>,
	<p className='bold tar'>Rapaz mas é uma coisa triste viu. Muito ruim. É ruim demais.</p>,
	<br/>,
	<p>ele chamava, dizia, procurava ela e onde eu tava e ela não dizia e ele tirava a camisa ficava lá chorando. Chorando as lágrimas na camisa.</p>,
	<br/>,
	<p className='bold tar'>É duro, a pessoa gostar de alguém é muito ruim. Quer dizer, é bom quando a pessoa da certo assim né.</p>,
	<br/>,
	<p>Que nem o outro né. O outro gostava tanto de mim. Ave Maria. Mulher, o outro me levava café na cama e eu nunca consegui gostar do cabra.  </p>,
	<br/>,
	<p className='bold tar'>Não conseguia.</p>,
	<br/>,
	<p>Nunca nunca nunca. </p>,
	<br/>,
	<p className='bold tar'>Era um negócio que era uma tragédia mesmo.</p>,
	<br/>,
	<p>Você acredita, como existe Jesus, que eu não estou mentindo, que nos passava de duas horas duas e meia três horas só rodando uma mesa assim, uma mesa redonda rodando, ele querendo que eu fosse dormir mais ele e eu sem querer. Rodando rodando. Era. Até que ele desistia. Era.</p>,
	<br/>,
	<p className='bold tar'>Eu não sei como que não houve uma tragédia, viu. Rapaz, é perigoso.</p>,
	<br/>,
	<p>Eu dizia eu cozinho, eu lavo, eu arrumo, eu faço tudo pra você mas busca outra mulher? Não vem me procurar não que eu não quero você. Não gosto de você. E era bom mulher, bom bom que assim seja pra Deus, mas eu não tinha amor a ele. Foi tanto que no dia de eu ir embora com esse aqui eu disse a ele eu vou embora agora disse tu fica com tudo com casa.  Eu fui dormir no chão que nem aqui ó, nem pano tinha. Deixei minha casa com tudo, arrumada com tudo. </p>,
	<br/>,
	<p className='bold tar'>Foi, isso aí aconteceu mesmo.</p>,
	<br/>,
	<p>Eu digo eu não quero mais você, sabe porque eu não quero? Porque agora hoje, quando eu vi ele eu fiquei doida, eu digo hoje eu observei, que se eu ficar com você, você não merece ser um homem traído. E se eu ficar com você eu vou trair. E eu não quero fazer isso. Eu vou embora. Eu deixo tudo. Tô deixando você com tudo aí. Venda, faça o que você quiser com tudo aí. Quero nada seu. Não quero você não quero nada seu. </p>,
	<br/>,
	<p className='bold tar'>Ela escapou disso foi muita sorte porque tem a maior parte dos casos desse acontece tragédia. </p>,
	<br/>,
	<p className='tar'>– Mata?</p>,
	<br/>,
	<p>Mata.</p>,
	<br/>,
	<p className='bold'>mata, é muito difícil pra sair. Isso é uma coisa que vai ficar na pré historia uma coisa dessa.</p>,
	<br/>,
	<p>Mas se matasse matava uma mulher. Mas eu não fiz nada de errado</p>,
	<br/>,
	<p className='bold tar'>Porque isso aí é muito perigoso. </p>,
	<br/>,
	<p>nem sai escondido. Eu não sai escondido não, eu tinha que dizer a ele a verdade, né?</p>,
	<br/>,
	<p className='bold tar'>Foi. Falou. </p>,
	<br/>,
	<p>Porque se eu não correr pela verdade eu morro. Qualquer hora.</p>,
	<br/>,
	<p className='bold tar'>Mas tem pessoas que mesmo falando a verdade não aceita.</p>,
	<br/>,
	<p>Eu sou assim, meu pai, meu pai é aquela fotografia lá ó. Meu véinho. Ele sempre ele dizia</p>,
	<br/>,
	<p className='bold tar'>Morreu já. </p>,
	<br/>,
	<p>sempre ele dizia, ele era bem magrinho que nem meu menino. E sempre ele dizia – minha filha, o que você vai passar na sua vida, sofrimento, é por você ser muito verdadeira. Que nem tudo você pode falar. Mas eu vou mentir?! Eu não! Nem que eu morra, mas eu morro com a elegância. Se quiser me matar pela verdade problema de quem quiser. Mas não vou me morrer covarde não eu vou falar a verdade. Cheguei e ele disse – você vai embora?</p>,
	<p>Eu digo eu vou embora você arrume outra, arruma outra pessoa que eu não sou, você precisa e você merece alguém que te ame. Eu não te amo. Então vou ficar com você? Eu digo  já vivi dez anos de sacrifício, então não vou viver mais não, agora que eu vi a pessoa que eu gosto meu amigo você vai ficando por ai. Eu digo se você quiser na onde eu tiver eu escrevo pra você. Quando você arrumar uma pessoa que você quiser eu desquito eu divórcio, o que  você quiser. Pode vir que eu assino. E eu queria vir eu, eu com um buchão bem grandão desse eu queria vir assinar e ele não queria deixar eu assinar. O desquito.</p>,
	<br/>,
	<p className='bold tar'>Esse negocio ai rapaz não dava certo não.</p>,
	<br/>,
	<p>Eu queria vir eu assinar o desquito, o divórcio e ele não queria. Eu queria vim desquitar, mas ele não deixava com medo dele me matar.</p>,
	<br/>,
	<p className='bold tar'>Isso ai é muito perigoso, </p>,
	<br/>,
	<p>Ai terminaram matando ele.</p>,
	<br/>,
	<p className='bold tar'>não dava certo não.</p>,
	<br/>,
	<p>Mataram ele porque ele arrumou uma mulher que tinha marido.</p>,
	<br/>,
	<p className='bold tar'>Rapaz ele deu de cara com uma mulher que tinha ela tinha um marido ai rapaz e o camarada era muito violento e a gente nessa época a gente não morava, a gente tava em Aracaju.</p>,
	<br/>,
	<p>Eu tava grávida daquele, do moreninho.</p>,
	<br/>,
	<p className='bold tar'>Desse moreninho que estava aí. Nós tem um moreninho que puxou ela e tem um outro branquinho que já puxou pra mim também a menina também. É.</p>,
	<br/>,
	<br/>,
	<p>Mas é. A minha história toda é essa.</p>
];