import React from 'react';

export default [
	<p className='bold text-font-big text-uppercase'>Contrato</p>,
	<br/>,
	<p>Quase uma semana que nós ficou em um hotel lá esperando uma decisão.</p>,
	<br/>,
	<p className='tar'>Debaixo de ordem. Qualquer hora que eles ligassem chamando o pessoal vinha aqui nós tinha que ir conversar com ele. Do ministério. Lá dentro do ministério mesmo.</p>,
	<br/>,
	<p>E nisso, uns cara mala da porra, ameaçando e tudo....</p>,
	<br/>,
	<p className='tar'>tinha um cara da OAS que só vivia de olho na gente. Trocando ideia, querendo saber se descobria alguma coisa. Querendo jogar ideia na galera.</p>,
	<br/>,
	<p>Tu ficou naquele hotel, no... esqueci até o nome. Que os carinhas do Corinthians foi lá? Tu ficou nele ou não?</p>,
	<br/>,
	<p className='tar'>Fiquei. Ficou tu, teu pai... nós tava tudo junto.</p>,
	<br/>,
	<p>Foi. Foi. Então, nós ficamos e chegou os moleques do Corinthians do subdezessete. Jogaram a final e perderam e ficaram lá. Uma molecada lá. Assistimos eles lá jogando,  não jogavam nem metade lá do que eu jogava mãe. Só empolgação.</p>,
	<br/>,
	<p className='tar'>Tudo boy tudo boy tudo boy.</p>,
	<br/>,
	<p>É só boyzinho. Todo tatuadinho, cheio de deixe me deixe na boa. O lateralzinho esquerda que era o mais empolgado. Nós na fé, assiste. Não deu nada né. Perderam, ficou feio. Aí veio eles em cima. Tinha cara da OAS também. Invocando mesmo. Tirando onda. Uma voz foi chamando Alex, uma foi chamando Naldo meu irmão e outra foi</p>,
	<br/>,
	<p className='tar'>chamando pra descer porque tinha alguém chamando</p>,
	<br/>,
	<p>pra descer na porta do hotel, olha. E outra querendo que mais quatorze querendo saber onde nós tava pra ir lá conversar com ele. Eu já sabia que era querendo fazer a mente dele, pra ele vir falar comigo pra baixar a poeira no movimento...</p>,
	<br/>,
	<p>é que ela queria puxar um pra ver se esse um conversava com os outro pra poder abafar o caso, diminuir sei lá. Jogando ideia na turma pra ver se o negócio acabava por ali. Mas só que o negócio já tava bem é evoluído.</p>,
	<br/>,
	<p>Era. Pra não cair na OAS com força.</p>,
	<br/>,
	<p className='tar'>Porque disse que tinha um cara da OAS junto lá, era? Também?</p>,
	<br/>,
	<p className='tar'>Tinha, tinha. Ele chegava direto de olho na gente.</p>,
	<br/>,
	<p>Era rapaz, na moral. Por isso que a casa caiu com o cabra falando que eu ia arrumar problema. Certo. Aquele doidinho da OAS, olha. Eu não sei o que ele pegou Alex botou Alex pra assinar um papel, olha. Folha grande. No corredor, que eu fiquei no quinto é pro sexto andar, aí ele botou Alex pra assinar aí Alex vacilão foi aí e assinou sendo que ele dormia no quarto vizinho. Dos amigos meu. Eu tava mais Naldo, pai, Marquinho aí esse aí ficou mais catorze. Quando dá fé lá eu cheguei quase dentro da OAS e perguntei <span className='italic'>você assinou um papel?</span> – Eu <span className='italic'>eu assinei</span>. Eu digo: <span className='italic'>como é?</span> Sendo que o negão advogado já tinha dito que nós não desse uma palavra com eles. Eu digo: <span className='italic'>cadê ele?</span> Ele desceu a porta e eu peguei o elevador e disse <span className='italic'>vamos!</span> Fui eu e ele pro térreo, um atrás, chegando lá quando o elevador desceu aí ele querendo ir pro quarto dele. <span className='italic'>E aí doidinho?</span> Ele se assustou quando olhou aí veio, <span className='italic'>venha cá!</span> Aí ele veio ... deixa eu ver o papel que você assinou. – <span className='italic'>Não, não tá aqui comigo é porque é coisa de outro negócio...</span> E eu <span className='italic'>o quê? Tem cinquenta e seis pessoas aqui, alojada, por esse rolo aí, tu vai e bota o cara pra alastra o quê? – Não, não sei o que...</span> aí quando eu olhei eu digo <span className='italic'>passa o papel vai, passa!</span> Manda manda manda. Ele entregou na hora. Rasguei. Joguei no lixo. <span className='italic'>Então dá uma palavra aqui com a galera não e já era. Agora é só os advogado do Sindicato e vocês aí de boa.</span></p>,
	<br/>,
	<p className='tar'>É tem que deixar o negócio acontecer com eles lá, porque a gente já tinha alguém pra resolver isso aí e a gente não precisava fazer nada disso aí não.</p>,
	<br/>,
	<p>Porque o negócio eu já disse olha. Você não pode dar uma palavra com eles. Por isso que as coisas são complicadas.</p>
];