import React from 'react';

export default [
	<p className='bold text-font-big text-uppercase'>DINHEIRO TRAVADO, TRABALHADOR BARRADO</p>,
	<br/>,
	<p>Foi só do meio em diante. No começo não, no começo até que beleza, né? Enquanto a gente tava na casa lá, alugada né. Aí depois de que a gente saiu pros hotéis lá, aí complicou tudo.</p>,
	<br/>,
	<p className='tar'>– Mas você recebeu já a indenização?</p>,
	<br/>,
	<p>Nada. Até hoje. Tá no advogado.</p>,
	<br/>,
	<p className='tar'>– Mas a maioria recebeu, não?</p>,
	<br/>,
	<p>Bem dizer todo mundo já recebeu, tem gente aí que não colocou advogado e já recebeu e eu não recebi. </p>,
	<br/>,
	<p className='tar'>– Nem o P.</p>,
	<br/>,
	<p>Também não. Mas o P. ele veio colocar advogado tá com o quê, tá com seis a sete meses. Ele veio ele não ia nem colocar. Ele não queria colocar. Aí  o interessante é isso. Eu conheço, dos que foram lá, que ainda falam comigo, vários, que ainda não colocaram advogado e receberam. Finalzinho do ano passado agora. </p>,
	<br/>,
	<p className='tar'>– E o advogado fala o porque disso?</p>,
	<br/>,
	<p>Só fala que tá lá bloqueado no TST eles vão julgar lá não sei o que e até hoje. E é o advogado de todo mundo dos outros tudinho é o mesmo advogado.</p>,
	<br/>,
	<p className='tar'>– O dinheiro tá travado?</p>,
	<br/>,
	<p>Aham.</p>,
	<br/>,
	<p className='tar'>– A OAS já deu esse dinheiro?</p>,
	<br/>,
	<p>Uma parte.</p>,
	<br/>,
	<p className='tar'>– Só que o dinheiro não chega pra vocês?</p>,
	<br/>,
	<p>Não chega de jeito nenhum. Tá lá travado no TST.</p>,
	<br/>,
	<p className='tar'>– Será que o povo desvia?</p>,
	<br/>,
	<p>Não, eu tô achando que foi a juíza de Salgueiro.</p>,
	<br/>,
	<p className='tar'>– Que desviou?</p>,
	<br/>,
	<p>Não. Ela trava algumas coisas. Lá o do meu primo mesmo que tava comigo, foi liberado agora a poucos dias. O dele tava travado passou um ano travado com a juíza de lá. De Salgueiro.</p>,
	<br/>,
	<p className='tar'>– Então ainda pode ser que vocês recebam.</p>,
	<br/>,
	<p>Pode ser. É por isso que eu tô esperando, mas eu não tô com muita esperança não. Eu mesmo já fui no advogado duas vezes pra ele tirar. Porque se ele tirasse eu tinha conseguido trabalhar de novo. Eu sou encarregado de obra e de lá pra cá eu não consegui mais trabalhar.</p>,
	<br/>,
	<p className='tar'>– Mas os caras que receberam já conseguem trabalhar?</p>,
	<br/>,
	<p>Já! Tão tudo no meio do mundo. Só tá aqui dos que, é por isso que eu vou dizer pra vocês, vocês vão achar poucas pessoas do que tavam lá, viu. A maioria tudinho tá no meio do mundo.</p>,
	<br/>,
	<p className='tar'>– Quantos?</p>,
	<br/>,
	<p>Você achar sete, oito vai ser muito. A maioria desse pessoal eu perdi contato depois desse negócio aí. E o pior é que depois de tudo quando chegou aqui a maioria achou que eu que tinha ferrado com eles, eu disse meu amigo, eu fui junto, tava mais vocês na casa lá. Agora se eu fizesse que nem os caras de lá queria que eu fizesse, aí eles iam se ferrar. Na hora que eu tava lá eles vieram com o carro lá e queriam me tirar de lá da casa, levar pra um canto e eles que se virassem. Com tudo. Quem foi que correu atrás do Ministério do Trabalho, de Sindicato foi tudo eu, e no final das contas eu me ferrei todinho. </p>
];