import React from 'react';

export default [
	<p>A gente tem que colocar na cabeça que só em a gente viver já é perigoso.</p>,
	<br/>,
	<p className='bold tar'>Isso aí é mesmo é perigoso.</p>,
	<br/>,
	<p>Porque quem não quer sofrer tem que nascer morto. </p>,
	<br/>,
	<p>Mas é. Não, isso é verdade.</p>,
	<br/>,
	<p className='bold tar'>Nasceu vivo com os óinho aberto </p>,
	<br/>,
	<p>Mas isso é verdade.</p>,
	<br/>,
	<p className='bold tar'>vai enfrentar problema. Não adianta ter medo de nada, </p>,
	<br/>,
	<p>Mas isso é verdade.</p>,
	<br/>,
	<p className='bold tar'>porque quanto mais você tem medo das coisas, mais as coisa vem aí abusando de você.</p>,
	<br/>,
	<p>Mas isso é verdade, mas acontece é que...</p>,
	<br/>,
	<p className='bold tar'>De bicho nenhum você pode ter medo. Quando ele vinher é pra você... você acredita que eu já peguei na mão do demônio?</p>,
	<br/>,
	<p>Olha. Ela aqui é o seguinte </p>,
	<br/>,
	<p className='bold tar'>Ninguém pode acreditar isso </p>,
	<br/>,
	<p>é uma coisa que</p>,
	<br/>,
	<p className='bold tar'>mas Jesus é o primeiro a saber que aquilo não era gente não. Aquilo era demônio. </p>,
	<br/>,
	<p>é uma coisa que significando aquilo nós vamos trocar por, assim... o assunto.</p>,
	<br/>,
	<p className='tac'>– Em São Paulo?</p>,
	<br/>,
	<p>Não. Nada. Em São Paulo nada. No sítio onde eu morava, com meu pai e minha mãe.</p>,
	<br/>,
	<p className='bold tar'>Que ela já pegou na mão do capeta. É verdade! Mas é verdade! Ela vai contar agora!</p>,
	<br/>,
	<p>Deixa eu falar uma coisa. Muitas pessoas</p>,
	<br/>,
	<p className='bold tar'>Olha:</p>,
	<br/>,
	<p>muitas pessoas gosta de chamar, falar aqueles palavrão, chamar pelo demônio, chamar pela... muita gente gosta de chamar aquele nome</p>,
	<br/>,
	<p className='bold tar'>raio de não sei de quê. Raio de não sei de quê.</p>,
	<br/>,
	<p>Lá eles falam desgraça</p>,
	<br/>,
	<p className='bold tar'>aqui ninguém fala isso.</p>,
	<br/>,
	<p>e fala raio de não sei de quê, raio de não sei de quê. </p>,
	<br/>,
	<p className='bold tar'>A gente não fala esse nome aqui não.</p>,
	<br/>,
	<p>A gente, se apegando com Deus, a gente já enfrenta problema, quanto mais chamando por quem não presta e por quem não é nada. Que não tem nada. Eles não tem nem pra eles próprio, quanto mais pra dá pra ninguém. Entendeu? Deus tenha minha mãe lá e ela não sofra pelo o que eu tô falando. Mas ela sabe, onde ela tá, que eu tô certa. 
	</p>,
	<br/>,
	<p className='bold tar'>É que a mãe dela já morreu o pai dela também morreu também já.</p>,
	<br/>,
	<p>Minha mãe é falecida. Mas minha mãe tinha mania, você sabe o que é habito? Pessoas que pegam o sexto de tudo o que fala é com nome na boca chamando palavrão? </p>,
	<br/>,
	<p className='bold tar'>Tem gente que é assim: raio de não sei o quê raio de não dei o quê.. isso aí é uma coisa.. isso aí é feio. Isso é</p>,
	<br/>,
	<p>Minha mãe era assim. Ela chamava bexiga, chamava peste, chamava não sei o quê. E é aquilo. E você sabe que Deus disse “pelas abelha de São Pedro, paga de São Paulo de todos os santos”. Às vezes você faz uma coisa onde você não vai pagar. Quem vai pagar é o teu filho. Entendeu? 
	</p>,
	<br/>,
	<p className='bold tar'>É.. às vezes até uma família dele..</p>,
	<br/>,
	<p>Vai no que você mais, na dor que você sente mais. </p>,
	<br/>,
	<p className='bold tar'>É.. e é perigoso mesmo.</p>,
	<br/>,
	<p>Meu pai e minha mãe, era uma época ruim não era uma época assim chuvosa, era uma época que nem agora. E nós criava muitos animal. Bode, carneiro. Sabe? Aí tinha umas, era uma época que não chovia, aí tinha uma.. elas não sabe não, mas eu sei que você sabe. Você conhece uma árvore por nome de quixabeira?
	</p>,
	<br/>,
	<p className='tac'>– Conheço.</p>,
	<br/>,
	<p>Que tem uns espinho?</p>,
	<br/>,
	<p className='tac'>– Conheço.</p>,
	<br/>,
	<p>Aquela rama </p>,
	<br/>,
	<p className='bold tar'>quixabeira...</p>,
	<br/>,
	<p>sempre quando era assim umas nove pra dez hora do dia, mamãe terminava de fazer o café dava café a nós tudo que nós somos sete irmão, aí mãe pegava uma foice ou um facão, aí dizia – eu vou tirar rama de quixabeira pras ovelha. Quando a gente tinha umas ovelha enjeitada que a gente criava - elas não sabe ou pode não saber o que é enjeitada - enjeitada é você criar aquele animal assim na mamadeira dando leite na mamadeira, que nem dá a uma criança.
	</p>,
	<br/>,
	<p className='bold tar'>É, um animal. Tem gente que cria animal enjeitado a leite.</p>,
	<br/>,
	<p>Aí eles cresce, sabe? Onde a gente vai eles vai atrás. Aí tinha uma meia dúzia de cabrita assim que às vezes a mãe morria, morria de parto, morria de bicheira. E sempre a gente criava eles assim na mamadeira. E eles ficava assim a onde mamãe chamava – bitinho bitinho eles saia acompanhando mamãe correndo atrás. Ai a mainha pegava a... e era uma época de Carnaval, por isso que eu digo que era o demônio e eu não gosto de Carnaval por conta disso eu sabia que era o demônio por conta daquilo, escuta só.
	</p>,
	<br/>,
	<p className='bold tar'>Era uma época de Carnaval. </p>,
	<br/>,
	<p>No sítio</p>,
	<br/>,
	<p className='bold tar'>Mas Carnaval</p>,
	<br/>,
	<p>no sítio</p>,
	<br/>,
	<p className='bold tar'>simboliza festa do demônio mesmo.</p>,
	<br/>,
	<p>Casas difícil de uma longíssima de uma pra outra. Casas assim ó, vocês vinheram pela orla, não foi? Pronto, uma casa aqui outra lá se aproximando da orla, outro se aproximando lá na orla, outros na mesma distância. Longe. Afastado. Num era um povoado, era um sitio zinho. Com poucas casa. Isso era um dia de sábado.
	</p>,
	<br/>,
	<p className='bold tar'>Sábado.</p>,
	<br/>,
	<p>Sábado que no domingo era Zé Pereira. O pessoal na cidade já tava tudo se aproximando pra o Carnaval. </p>,
	<br/>,
	<p className='bold tar'>Geralmente o Carnaval tem sábado que é Carnaval e domingo Zé Pereira.</p>,
	<br/>,
	<p>Aí eu peguei... tinha uma rede assim armada na sala, a sala era uma sala grande com uma rede assim armada na sala, e eu tinha mais duas irmã. Nós somos sete mais as duas irmã. Eu peguei a rede, eu fiz como se fosse a rede fosse, fosse uma canoa, um barco. Né? Eu fiquei assim do lado de um pulo da rede, a minha irmã, a outra, encostada ali do outro lado e eu botei a pequenininha assim no meio da rede. E fique cantando, mamãe saiu pra tirar as quixabeira, as rama de quixabeira para os cabrito, pros bode, e eu fiquei cantando. Eu lembro que nem hoje eu cantando
	</p>,
	<br/>,
	<p className='bold tar'>Se lembra que nem hoje!</p>,
	<br/>,
	<p>Fazendo como se a rede fosse uma canoa. </p>,
	<br/>,
	<p className='bold tar'>É mole? É mole? Lembra. Hoje!</p>,
	<br/>,
	<p className='italic'>
	Canoeiro canoeiro 
	<br/>
	o que é que traz nessa canoa? 
	<br/>
	Trago ouro
	<br/>
	 trago prata
	<br/>
	 trago muita coisa boa.
 	</p>,
	<br/>,
	<p>Eu balançando na rede com a minha irmã, a Pequenininha. Ela se apenas se sentava. Entendeu? Mas ela também demorou muito a andar, ela já tinha uns nove pra dez meses. Aí quando mamãe, mamãe disse que olhou... olhe só, que minha mãe era uma senhora de coragem viu? Ela disse que olhou assim e era que nem uma reta, uma estrada. Estrada de chão né? Ela disse que olhou assim pra reta, ela disse que viu aquela coisa mais fêa, aquele coiso escuro, preto, umas dez hora do dia. Coisa mais horrível. O que foi que mãe fez? Que quixabeira tem espinho. Mamãe viu ele distante assim mamãe baixou logo com um facão mesmo tirou os espinhos mais ou menos e pulou: subiu em cima da quixabeira. Ele fez, você vê ó: ele fez um rapapé tão grande, batendo os pé ao redor donde os bicho tavam comendo as ramas e os bichos correram. Papai perdeu esses bichos tudinho. Eles nunca mais apareceram.
	</p>,
	<br/>,
	<p className='bold tar'>Os que correram nunca achou até hoje. </p>,
	<br/>,
	<p>Nunca apareceram.</p>,
	<br/>,
	<p className='bold tar'>É mole? Nunca apareceram até hoje.</p>,
	<br/>,
	<p>E o cara fez aquele sapateado todo e caminhou como se fosse pra casa de mamãe.</p>,
	<br/>,
	<p className='tac'>–  Mas por que? Mas isso era um homem de verdade?</p>,
	<br/>,
	<p>Eu digo que era o demônio. Eu digo que não era homem um negócio daquele. Escute só a pantoria. </p>,
	<br/>,
	<p className='bold tar'>Olha se era gente de verdade:</p>,
	<br/>,
	<p>Eu ia fazer doze anos. Aí quando mamãe disse - eu acho que esse bicho (mamãe pensou que fosse um bicho) esse bicho vai comer é meus filhos, mas eu não vou.. mas eu não vou atrás. Eu não vou atrás (que mamãe não tem coragem, mamãe perdeu a coragem). Quando mamãe chegou que viu ele saindo mamãe só ficou no medo que ele ia pegar a gente, mas escuta só: a casa da gente não era, a casa de sítio é uma casa de madeira, uma porta de madeira, entendeu? A porta mais ou menos aqui ó, aqui assim...duas portas. Abre uma e fica outra. Essa aqui debaixo estava fechada e essa outra estava aberta. Quando ele chegou na porta você vendo, pra você ver que não era nem porta.
	</p>,
	<br/>,
	<p className='tar'>Porta de fazenda é assim</p>,
	<br/>,
	<p>ela é metade metade</p>,
	<br/>,
	<p className='tar'>dividida. Essa aqui fica fechada e essa fica aberta</p>,
	<br/>,
	<p>tipo uma janela. Aí quando eu na rede eu cantando com a menina, eu e minha outra irmã, a Pequenininha, pra você ver, a Pequenininha se assombrou tanto só bateu assim na rede sabe? 
	</p>,
	<br/>,
	<p className='bold tar'>A Pequenininha que ela tava balançando até hoje ela é irmã dela. Ela mora numa agrovila. Chama Lurdinha.</p>,
	<br/>,
	<p>Aí eu vi a casa escurecer né. Eu vi a casa escurecer. Quando eu vi a casa escurecer eu cantando e balançando tranquilo, eu vi aquela casa escura assim, aí eu olhei pra porta. Quando eu olhei pra porta, então, tava aquela coisa mais horrível do mundo. Que aquilo não era gente desse mundo, eu garanto que não era. 
	</p>,
	<br/>,
	<p className='bold tar'>Não era não.</p>,
	<br/>,
	<p>Agora se fosse hoje, nega véia, hoje eu peitava com ele, ele podia vim do jeito que ele vinhesse! Mas eu era criança e aquilo não foi por conta de nada era pelo nome que mamãe dizia. Quem foi pagar foi eu. Aí ele foi. Quando ele foi chegando o bicho era tão preto tão esquisito e tão cabeludo, você não vê 
	</p>,
	<br/>,
	<p>– Antigamente não tinha lobisomem?</p>,
	<br/>,
	<p className='bold tar'>É o capeta meu filho. Mas tem o capeta na terra mesmo. O capeta na terra. Tem o capeta na terra.</p>,
	<br/>,
	<p>Escuta só: quando eu vi ele... Ele pegou, olha, pra você ver, quando eu olhei pra fora que eu vi ele, que eu olhei, que eu vi aquela ciosa mais horrível do mundo. Preto mas era preto que era requinto mesmo que nem piche. E a sobrancelha vermelha e a boca vermelha e os dentes vermelhos. 
	</p>,
	<br/>,
	<p className='tac'>–  Uma pessoa pintada</p>,
	<br/>,
	<p>Era nada. Que pessoa? E depois na mesma hora com o grito que eu dei? </p>,
	<br/>,
	<p className='bold tar'>Meu filho, tá de brincadeira? Esse cara era o capeta rapaz!</p>,
	<br/>,
	<p>E todo mundo foi atrás e nem rastro nem nada. </p>,
	<br/>,
	<p className='tac'>–  Sua mãe viu também?</p>,
	<br/>,
	<p>Mamãe viu. Só que mamãe ficou em cima da quixabeira. Ela não teve coragem de descer. E ele chegou.. pra você ver a minha inocência: a minha inocência que eu cheguei e eu disse assim. Quando ele botou, olhou firme assim com aqueles olhão, mesmo, aí ele botou a mão no ferrolho da porta
	</p>,
	<br/>,
	<p className='bold tar'>Ainda botou a mão no ferrolho. É mole?</p>,
	<br/>,
	<p>uma fechadura. Quando ele botou a mão no ferrolho que ele disse –  eu vou pegar a sua irmã! Quando ele falou assim, você pode acreditar como existe Jesus no céu, como eu me levantei dessa rede eu fui a caminho de encontrar com ele pra com medo dele pegar minha irmã. Mas eu não senti que eu pisava no chão. Eu senti que eu ia assim ó: como quem eu ia
	</p>,
	<br/>,
	<p className='bold tar'>numa câmara lenta</p>,
	<br/>,
	<p>na câmara lenta sabe? Aí eu cheguei pra você ver como a minha inocência foi tão grande que eu cheguei eu disse bem assim: bença. Quando eu falei bença, olha pra você ver, eu acho que Jesus só me abençoou com aquele bicho porque eu tomei a banção. Quando eu disse bença ele na minha mão ele não pegou, mas deu uma risada tão horrível, sabe? Não sei se foi da minha inocência porque eu tomei benção, não sei que foi que ele achou tão bonito de dar uma risada tão grande daquela. Mas eu tirei num grito e ele deu um rodete assim e saiu como quem era um monte de palha assim ó. Ventava. Era uma palha preta como quem era assim...
	</p>,
	<br/>,
	<p className='bold tar'>O meu corpo chega arrepia um pouco.</p>,
	<br/>,
	<p>E eu dei um grito tão grande que chegou os vizinhos tudinho a cavalo. Os vizinhos tudinho a cavalo rodaram rodaram e não acompanharam ele, nem acompanharam. Foram na quixabinha na outra, no outro vizinho. E passou lá e disseram que não passou lá. E nem rastro.E eu digo que era o demônio porque os pés dele não era que nem pé de gente. Entendeu? Era que nem pé de pato e assim ó.
	</p>,
	<br/>,
	<p className='bold tar'>É o capeta. Capeta tem o pé assim. Mas é. E pé de pato também. O Capeta.</p>,
	<br/>,
	<p>Eu digo que que já peguei na mão do bicho.</p>
];