import React from 'react';

export default [
	<p className='bold text-font-big text-uppercase'>PARTIDO AO MEIO </p>,
	<br/>,
	<p>Se você for analisar, se pesquisar a fundo, São Paulo em si, os demais eu não sei, mas 70% da mão de obra do que foi pra fazer São Paulo, foi o povo nordestino. </p>,
	<br/>,
	<p className='tar'>Brasília também, Nildo.</p>,
	<br/>,
	<p className='tac'>– Brasília vieram de vários lugares, não é?  Brasília faz tempo já, você não foi pra lá, né?</p>,
	<br/>,
	<p className='tar'>Não. Brasília eu não tive não. Quer dizer, eu já passei assim, de passagem em Brasília. Mas pra trabalhar lá não.</p>,
	<br/>,
	<p>São Paulo esse tempo que a gente tem, quinze dezesseis anos de trecho, conheci. E bons. Tem. Agora muito poucos, trabalhador da construção civil. </p>,
	<br/>,
	<p className='tar'>Brasília é muito é bonito, né Nildo? Brasília é bonito demais.</p>,
	<br/>,
	<p className='tar'>– Mas sabe que Brasília morreram muitos trabalhadores durante a construção.</p>,
	<br/>,
	<p>Foi. </p>,
	<br/>,
	<p className='tar'>– Parece que eles eram até concretados... porque tava construindo e eles caíam lá de cima, no concreto, e tinha tanta pressa pra construir.</p>,
	<br/>,
	<p>Isso. A gente manja muito disso aí que isso vem de barragem. </p>,
	<br/>,
	<p className='tar'>Em barragem também!</p>,
	<br/>,
	<p className='tar'>Concretava na obra. O corpo!</p>,
	<br/>,
	<p>É chamado concreto gelado: bateu secou.  </p>,
	<br/>,
	<p className='tar'>– Isso é concreto gelado?</p>,
	<br/>,
	<p>É, chama concreto gelado. É um produto que eles coloca. Tem um produto específico pra colocar no concreto que ele seca automaticamente muito rápido. Tá entendendo? Olha, nessa barragem que, na Luis Gonzaga de Itaparica, essa de Paulo Afonso, a de Xingó, que é as mais antigas do Brasil. Itaipu. Considerada a maior do Brasil, porque aquela outra que é muito famosa também, o Brasil divide ela, não sei se não me engano, com Paraguai, não é? Pra gerar pros dois país. Não é considerada totalmente do Brasil, é uma pai, ela é maior do que Itaipu. </p>,
	<br/>,
	<p className='tar'>É maior. Tem um nome dela mesmo, é.</p>,
	<br/>,
	<p>Ela tem 22 a 24 turbinas pai. Ela é muito grande. Ela é maior do que Itaipu. Só que ela gera pra nós, o Brasil e pro Paraguai. Conhecida. Então automaticamente conheci a considerada maior do Brasil, Itaipu. Que ela é toda do Brasil. Esqueci o nome, um nominho simples, uma palavrinha pequena. Então, mas todas essas morreu peão demais. Mas muito gente com força. </p>,
	<br/>,
	<p className='tar'>– E caia no concreto e ficava o corpo?</p>,
	<br/>,
	<p>Caia... não só no concreto mas de vários setor. Tanto da ferragem, da carpintaria. Porque não tinham um sistema de segurança que a gente tem hoje. Se for investir na construção civil um pouco um tanto até bom. Melhorou muito a segurança já. Mais dos últimos dez anos mais. Doze anos. </p>,
	<br/>,
	<p className='tar'>– Mas você acha que melhorou</p>,
	<br/>,
	<p>muito muito mesmo. </p>,
	<br/>,
	<p className='tar'>– Por quê?</p>,
	<br/>,
	<p>Por conta do, primeiro na verdade, o que muito ajudou: o próprio investimento porque morria gente demais e isso prejudicava e prejudica hoje em dia é bem complicado, olha. Uma empresa que morre, numa obra que morrer dois ou três funcionários... fica mais nada. E agora não tem mais, existe mais fiscalização, pega mais no pé. O próprio Ministério do Trabalho agora é mais rígido. Mas antigamente que nem foi pra fazer todas essas barragens mais antigas aí, não tinha fiscalização. Sumiu e mandava dizer pra família – <span className='italic'>ah o cara morreu aí no meio da rua. Morreu como um indigente. Morreu fora da obra.</span> </p>,
	<br/>,
	<p className='tar'>E o corpo desaparecido.</p>,
	<br/>,
	<p>E o corpo nunca que aparecia. Mas demais. Igual passou no Fantástico não sei se vocês tiveram acesso. Pai aquela ponte que liga acho que é a maior do Brasil, que liga... a ponte Rio Niterói. </p>,
	<br/>,
	<p className='tar'>A Rio Niterói ela tem, passa tem um movimento muito muito grande. Passa pelo estado da Bahia, vai pra Minas, entra em São Paulo, vai pra aquele bairro tudo do Rio de Janeiro. </p>,
	<br/>,
	<p>O Senhor acredita, pois eu vi no Fantástico, ainda existe uns dos poucos engenheiros, senhorzinho velho, magrinho. Ele abriu a boca e deu a cara pra bater no Fantástico mesmo. Ele disse que era em baixo, naqueles pilar, naquela base, ele disse que com certeza</p>,
	<br/>,
	<p className='tar'>com certeza!</p>,
	<br/>,
	<p>menos que quatrocentas pessoas não foi. Que tão tudo concretada lá embaixo. Quatrocentos corpos tem lá embaixo. Entre todos os pilares.</p>,
	<br/>,
	<p className='tar'>Rapaz. Desse tanto?</p>,
	<br/>,
	<p>O velho mesmo meteu a cara pra bater. Com força. Antigamente era o bicho. Lá em baixo. </p>,
	<br/>,
	<p className='tar'>– E vocês viram que várias leis trabalhista agora não vão existir mais?</p>,
	<br/>,
	<p>Então, agora nisso aí, nesse sentido na moral, aí melhorou muito. Mas muito mesmo. Porque teve muito investimento, tudo no setor de segurança. Mas melhorou com força. Melhorou muito. Agora não, agora tá bem melhor. Segurança.</p>,
	<br/>,
	<p className='tar'>– Não tem mais muita gente que morre em obra, tem?</p>,
	<br/>,
	<p>Tem! Muita muita não. Mas até hoje, eu trabalhei nesse Brasil já. Barragem. Só em barragem eu trabalhei de nove a dez barragem. Mas nunca teve uma que eu não passei pra não morrer. Dois, um, três. Todas morrem. De uma forma ou de outra. </p>,
	<br/>,
	<p className='tar'>– Então ainda não é seguro. </p>,
	<br/>,
	<p className='tar'>De qualquer maneira é porque é menos morte, né?</p>,
	<br/>,
	<p>É menos. É. o índice, nossa, 90% melhorou. Mas ainda tem falha. </p>,
	<br/>,
	<p className='tar'>Umas por negligência da falta de equipamentos, outras por negligência do funcionário mesmo.</p>,
	<br/>,
	<p>Pronto. A mais pura verdade. </p>,
	<br/>,
	<p className='tar'>Tá entendendo? Porque a empresa dá os IPI tudo, tem orientação de tudo como é que é, tem deles que não usam o cinto. Às vezes não gosta. Outros, sabe? Às vezes acontece. </p>,
	<br/>,
	<p>Em alguns casos, falta de treinamento, que nem o cara lá de onde o nosso filho nasceu, lá em Caçu, o rapaz do embutido que morreu, ali pai, um caso de pura falta de treinamento. Conhecimento. Rapaz morreu no setor do embutido. Beleza. Barragem é isso. É como muitas obras. O setor do embutido, as encanação hidráulica tem que subir da fundação até chegar em cima. Um tubo de acho que mil e duzentos, no metal, ele pra subir tem que emendar. Então beleza, as emendas. Mas quando até certo meio que vai concretar aí deixa uma sobra sempre a mais pra cima, ele pra não cair nada na tubulação, coloca uma tampa. Normal. Nessa tampa, é normal acontecer isso, então de dois a três pingos de solda: uma tampa, normal. Mas esse rapaz de lá que trabalhava com a gente, só que nesse período, eu tava pelo dia...</p>,
	<br/>,
	<p className='tar'>Tu conhecia ele, Nildo?</p>,
	<br/>,
	<p>Eu conheci ele. Moleque novo, ajudante ainda. Mas ele morreu a noite e eu tava pelo dia. Mas simplesmente é isso. Automaticamente encanação dessas coisas, ela vai gerando um ar por dentro. Gera ar, normal. E isso aquilo deu uma pressão muito grande. Ali faltou pura experiência, como é. Primeiro mais um erro gravíssimo é um ponto muito importante que é de trabalho: cada um na sua área. Cada um pra o que foi treinado que tá capacitado, cada um na tua área pra mexer. O moleque vai, erro começando dele próprio, que ele tinha que entender isso. O que não é da sua função você não pode fazer, erro principalmente do encarregado que deixou. Ele pegou o maçarico. Maçarico em obra só quem é qualificado pra mexer com maçarico ou soldador ou maçariqueiro. É isso que é colocado em sua carteira. É um profissional, que tem, na área. Então ele era um ... tanto, mas foi tirar a tampa pra poder desemendar. Daí é que você vê a falta de experiência. Cortou um ponto aqui olha, tá o cano aqui, ele no alto, realmente atracadinho pelo cinto, normal, mas na hora que ele tava cortando aqui com o maçarico cortou um ponto. Ele cortou um ponto, beleza. Agora se abriu, ela vai se abrir a tampa. Aí cortou o outro. O maçarico, você nunca viu não um maçarico?</p>,
	<br/>,
	<p className='tar'>– Já. </p>,
	<br/>,
	<p>Tem de várias formas. Tem maçarico de lanterneiro, que é para mexer com carro, ele é miudinho, diferenciado.</p>,
	<br/>,
	<p className='tar'>O maçarico é esse que corta o ferro e faz juntar e tudo?</p>,
	<br/>,
	<p>É, oxigênio e tudo. </p>,
	<br/>,
	<p className='tar'>– Maçarico é o que sai fogo?</p>,
	<br/>,
	<p>Isso. Quando usa ele, ao cortar qual é a lógica pra quem tem experiência....</p>,
	<br/>,
	<p className='tar'>E queima viu? E Nildo cortava de Maçarico chegava com as fardas tudo queimada.  E ainda queimava o coro. </p>,
	<br/>,
	<p>Ele foi cortar o segundo ponto, mas aqui ó, o cano aqui, sobre o cano mais alto, mas bem de cara. Qual é a lógica, pra quem tem experiência? Um profissional. Ficar de lado, que a mangueira é longa. O maçarico é mais ou menos desse tamanho. De barragem é do grande, assim.... você tem acesso ao ponto de solda. Não bota a carga. O moleque foi cortar o segundo ponto aqui ó. Quando ele cortou o segundo ponto, o último ponto não suportou: a tampa veio, de vez. Ela abriu o rosto dele, a cabeça dele no meio. Igual você partir uma melancia. Só por falta experiência. </p>,
	<br/>,
	<p className='tar'>Porque o lado que ele cortou o segundo ponto, o lado, a pressão veio com tudo.</p>,
	<br/>,
	<p>A pressão demais estourou o último ponto, sem dar tempo nem de cortar. Abriu a cabeça do cidadão, e ele ficou ele ficou pendurado assim, com a cabeça aberta que nem fosse uma melancia. </p>,
	<br/>,
	<p className='tar'>– Mas um homem que trabalha em construção civil, tipo esse menino de vinte e um, se é falta de experiência, experiência ele ganha trabalhando. Se arriscando. Mas poderia ter uma escola técnica, ou um lugar onde você pode cursar, aprender, simular situações sem que você tenha que aprender correndo o risco já. Porque a partir do momento que você tá aprendendo.... né?</p>,
	<br/>,
	<p>Cada obra grande dessa, tinha que realmente ter sua escolinha. Isso. </p>,
	<br/>,
	<p className='tar'>– Isso é um grande problema você ir aprendendo já na obra....</p>,
	<br/>,
	<p>Eu ainda não sei, se tem, eu não sei. Mas na verdade, de uma forma, aprendi mais na verdade de uma forma errada. Mas não existe nada da construção civil praticamente que eu não sei. Pode até ser, que sempre na nossa vida tem. Na nossa vida nós nunca sabe de tudo. Mas na construção civil, o que se possa imaginar de máquina eu mecho. Mas aprendi dessa forma. Na tora. </p>
];