import React from 'react';

export default [
	<p className='bold text-font-big text-uppercase'>RATOEIRA</p>,
	<br/>,
	<br/>,
	<p className='tar'>...Santa Catarina. Recebi uma proposta pra ir. Mil reais pra ir. Logo de cara: mil reais.</p>,
	<br/>,
	<p className=''>Não, também me deram essa proposta. E outra de setecentos. Eu digo <i>rapaz, bota na sua cabeça, se eu tivesse setecentos reais hoje livre no bolso eu ia pra onde?</i> </p>,
	<br/>,
	<p className='tar'>É, então.</p>,
	<br/>,
	<p className=''>Oxi tu é doido, é? Eu ia esperar é as coisas melhorar, véio. Ia não. </p>,
	<br/>,
	<p className='tar'>Uma coisa é certa, pois não melhora mais não. Infelizmente. Emprego, não melhora não. Se você não encarar a vida </p>,
	<br/>,
	<p className=''>Mas no caso do cabra botar, pegar mil conto e dar a um cara sem ele fazer praticamente nada não velho. Aí vamos supor, o cara chega lá aí da errado passa um mês trabalhando, não passa nem um mês a empresa bota o cabra pra fora de todo jeito, e aí? O cara ali dançou com mil reais. </p>,
	<br/>,
	<p className='tar'>Teve um rapaz aí que chegou aqui e levou, levou não, ele pegou dinheiro de uns trinta a quarenta peão. </p>,
	<br/>,
	<p className=''>Eu tava no meio.</p>,
	<br/>,
	<p className='tar'>Pegou o dinheiro e foi embora. Prejuízo. Prejuízo ele deu de uns nove a dez mil. Tem gente que na hora que ele chega aqui quer derrubar ele. Por causa de cem reais os cara quer derrubar ele.</p>,
	<br/>,
	<p className=''>Ele chegou pô, ele chegou ele pegou o dinheiro assim e disse – <i>ói, e quem não quiser ir o dinheiro tá aqui, ó! Tá aqui! Que eu sou um homem</i> não sei o que e espalhando dinheiro assim, – <i>quem quiser pegar o dinheiro de volta, pegue!</i> Falou na moral que eu digo virgem Maria, esse cara botei fé, o cara bota fé no cara, velho, desse jeito. Oxi, <i>botei fé nesse cara! Vou pegar o meu de volta não.</i> E a galera dizendo – <i>pega não, pô, o cara...</i> E o cara – <i>e amanhã pode tá aqui com as mala pronta. E eu tô dizendo de novo</i>, bateu o dinheiro na mão assim, – <i>quem quiser o dinheiro tá aqui o dinheiro de volta!</i> Meu amigo, a pacoteira de nota de cem, de cinquenta, de todo jeito, e os cabra ia descendo pra casa pra arrumar as mala, ó. Oxi. Foi no outro dia: <i>cadê o cara? – Oxi, pois o cara foi é se mandou foi de madrugada, aqui homem</i>. Disse que viram ele em Paulo Afonso, aí tomando uisque era do bom e derramando, velho. Disse que tava derramando uisque mesmo. </p>,
	<br/>,
	<p className='tar'>É só que é assim, se ele pisar aqui meu amigo, já era.</p>,
	<br/>,
	<p className=''>Pisa não, pô! </p>,
	<br/>,
	<p className='tar'>– E esse cara é quem?</p>,
	<br/>,
	<p className='tart'>É um agenciador. </p>,
	<br/>,
	<p className='tar'>– O mesmo de Guarulhos?</p>,
	<br/>,
	<p className='tar'>Não não não não. Esse que foi com a gente ele também foi no meio e ele rodou é igual a gente.</p>,
	<br/>,
	<p className=''>Foi.</p>
];