import React from 'react';

export default [
	<p className='bold text-font-big text-uppercase'>Em 21 de dez de 2016, às 17:13</p>,
	<br/>,
	<p>Oi João, tudo bem!?</p>,
	<p>Como anda a vida? </p>,
	<br/>,
	<p>estamos fazendo a rota da nossa viagem e lembramos de você.</p>,
	<p>se tiver alguma dica de cidade para parar, lugar para dormir, coisas para levar, </p>,
	<p>ia ser muito legal saber!</p>,
	<br/>,
	<p>e se você tiver um tempo ia ser gostoso marcar mais uma cerveja! o que você acha?</p>,
	<p>caso esteja ocupado nesse fim de ano podemos conversar por email mesmo.</p>,
	<br/>,
	<p>obrigada!!!</p>,
	<br/>,
	<p>ana e Isabella</p>,
	<br/>,
	<br/>,
	<p className='bold'>Em 23 de dez de 2016, às 18:47</p>,
	<br/>,
	<p>Olá a tod@s! </p>,
	<p>Está tudo bem, agora pelo menos. A anhembi é uma fonte inesgotável de surpresas, até ontem ainda estava lá assinando ponto, de uma aula sem alunos. </p>,
	<p>Mas passou, e agora as férias vem para trazer um pouco de tranquilidade e descanso. </p>,
	<p>Me desculpem não conseguir responder antes, o último email que trazia a discussão dos secundaristas, no excelente texto do Pelbart, merecia de fato mais umas cervejas para ser comentado. Assim como um papo sobre os caminhos que levam ao Norte, as cidades e os pequenos povoados a beira da estrada que tem uma arquitetura muito interessante, cheia de influencias vindas de vários lados. São ótimos casos de estudo, que um dia ainda volto a viajar para pesquisar isso mais de perto, assim como a particularidade (notem) de cada ponto de ônibus, o desenho que se desenvolve de acordo com aquilo que é de lá, ou mesmo aquilo que é trazido para lá. São identidades que revelam através da técnica construtiva, das cores, dos materiais aplicados mas também curiosamente através da imagem. Somente isso ja seria outro caso incrível de estudo, uma das coisas que me chamou atenção foi justamente a riqueza contida nas diferenças, mesmo sendo elas todas iguais. Isso me fez lembrar o trabalho maravilhoso do Christopher Herwig dos pontos de ônibus soviéticos ( http://fuel-design.com/publishing/soviet-bus-stops/ ) Tem um trecho de gravação com ele na estrada vale ver também ( http://herwigphoto.com/bs/ ). Me estimulou bastante e cheguei a iniciar um ensaio mas, o barato era que o vento levasse a ideia e não fazer com que a ideia fosse o vento. Então interrompi (mas confesso que esse ensaio tenha me influeciado bastante) e segui, mas não deixem de olhar para essas coisas, dei o exemplo do ponto de ônibus, da arquitetura, mas são as pessoas principalmente que fazem tudo ser bonito e espetacular. </p>,
	<p>Sobre os caminhos seria muito bom conversar com uma cerveja gelada e uma porção de tremoços. Conversaríamos sobre o mapa do brasil e suas estradas, porem até domingo não poderia, então se estiverem por ai e puderem segunda ou terça próxima seria uma boa para mim, a tarde mesmo pode ser. Do contrário me avisem que eu traço no mapa o percurso que ja fiz colocando os pontos importantes. </p>,
	<p>Lembro-me de ter comentado com vocês sobre a questão do perigo e da relação de medo que temos, e citei um texto muito interessante do Mia Couto. Esse não tenho link, vai o pdf anexo. </p>,
	<p>E vocês como estão!? Trabalhos finais de graduação concluídos com sucesso tenho certeza. Ao que posso dizer é que se não leram ainda o trabalho do Daniel, leiam. E aproveito mais uma vez a oportunidade, não só de parabeniza-lo mas também de dizer que tem sido uma grande satisfação acompanhar a construção de seu trabalho. </p>,
	<p>Me avisem, caso possam nos encontramos até terça pois quarta viajo, ou então em janeiro se ainda não tiverem ido, volto de viagem dia 05, ou mando por aqui mesmo alguns apontamentos sobre o mapa. </p>,
	<p>Até já!</p>,
	<br/>,
	<br/>,
	<p className='bold'>Em 7 de jan de 2017, às 18:07</p>,
	<br/>,
	<p>João! Como vai?! </p>,
	<br/>,
	<p>primeiro queria agradecer imensamente pelas referências e discussões. elas acabam por nos fazer viajantes desde já. numa viagem sem retorno! [ li essa frase hoje e achei muito linda :) ]</p>,
	<p>acho que no fundo esse trabalho é um movimento para encontrar, mas ao mesmo tempo os encontros movimentam nosso trabalho. por isso essas trocas são tão ricas pra gente.</p>,
	<br/>,
	<p>e tava lendo aqui o texto que você mandou  - murar o medo - ... demais. o trecho  "corpos convertidos em muro e pedra são uma metáfora do quanto o medo nos pode aprisionar" me lembrou a construção de Brasília.. onde muitos operários mortos foram concretados nas próprias construções. o tempo urgia para a cidade subir e ninguém parava pelos trabalhadores já mortos. acho que essa ideia do medo se torna potente também associando a ideia do tempo.. enfim! longa reflexão. </p>,
	<br/>,
	<p>podíamos continuar com uma cerveja, não?!</p>,
	<p>ia ser muito legal poder te encontrar antes de viajar.</p>,
	<br/>,
	<p>também achei demais o que você escreveu sobre os pontos de ônibus. são muitas coisas num território a se reparar que o tornam singular. mas ao mesmo tempo é interessante buscar a ideia do comum..</p>,
	<br/>,
	<br/>,
	<p>bom, mas como você está essa semana?!!</p>,
	<p>muito em cima? </p>,
	<p>nós podemos amanhã e segunda qualquer horário!</p>,
	<br/>,
	<p>aí depois a bé volta a trabalhar no restaurante e ela sai tardão. mas pode ser também :)</p>,
	<p>você topa?</p>,
	<br/>,
	<p>beijos e obrigada pelo email e referências.</p>,
	<p>amei!</p>,
	<br/>,
	<p>ana</p>
];