import React from 'react';

export default [
	<p className='bold text-font-big text-uppercase'>TRABALHO ESCRAVO: é o jeito que você fica, o jeito que você é tratado</p>,
	<br/>,
	<p className='tar'>– Eu queria perguntar pra vocês o que é trabalho escravo. Porque nas notícias sobre o caso falam que vocês estavam como escravos lá. Mas eu queria saber o que vocês acham  disso. Se concordam.</p>,
	<br/>,
	<p className='tar'>O que se tornou trabalho escravo aí foi esse negócio de a gente ir, foram prometendo uma coisa a gente </p>,
	<br/>,
	<p>e foi outra.</p>,
	<br/>,
	<p className='tar'>quando a gente chegou lá foi outra. Não é? A gente chegou lá, a gente já pagamos aqui, chegou lá a gente não tinha um emprego. E ainda ficamos jogados, que a empresa disse – Não, a gente não tem nada a ver com vocês não. Entendeu?</p>,
	<br/>,
	<p className='tar bold'>Todo mundo jogado que nem bicho dentro de uma casa lá.</p>,
	<br/>,
	<p className='tar'>Isso aí é onde tá o erro é esse aí. </p>,
	<br/>,
	<p>Porque o trabalho escravo ele não se torna trabalho escravo quando você trabalha. Ele se torna do jeito que você fica no local.</p>,
	<br/>,
	<p className='tar bold'>E do jeito que você é tratado também.</p>,
	<br/>,
	<p>Quando você é chamado pra uma obra, em escala, que é uma obra nacional, você é chamado de sua cidade pra outra, você tem toda a regalia. Tanto como sair daqui, a empresa ela tem direito de manter você daqui até lá. Quando a gente chegou lá, a gente nem casa, alugada tinha. A gente alugou na hora. Ficamos na frente da obra: descemos na frente da obra, é, cinco horas da manhã. Quando o povo começou a chegar ficaram olhando pra gente. O decepcionante não foi  o tanto a gente ficar lá na frente não. Foi o mau olhado dos outros, né. Olhava a gente como se a gente não fosse nada. Até que chegou um rapaz e falou – <i>ei, você são da onde?</i> A gente – <i>somos do Pernambuco</i>. – quem chamou vocês aqui? Aí a gente – <i>a OAS</i>. E ele – <i>não. A OAS não tá contratando não</i>. Aí eu digo <i>não</i>. Aí a gente falou o nome da pessoa, – <i>olha, quem chamou foi tal assim assim</i>. Aí teve um rapaz de uma empresa que tava precisando de dez armador, aí chamou, disse –olha, eu tô precisando de dez armador. Aí os dez foi. E os dez que entrou pra outra, que era da OAS, foi eu e mais nove, foi na onde a gente conseguimos pegar o documento, comprovar como a gente tava apto ao trabalho, só que assim, como a gente tá apto ao trabalho, </p>,
	<br/>,
	<p className='tart'>aí já tinha que receber. </p>,
	<br/>,
	<p className='tar bold'>Tinha que receber.</p>,
	<br/>,
	<p>Já tinha que, ela, já tinha que manter você. Mas não. Ela chegou pra gente e disse – <i>não. Vai pra sua casa e a gente liga pra você</i>. Aí se manteve como trabalho escravo por isso. Porque ela não manteve você. Ela não teve o compromisso de deixar você num local, apto, que era um local, por mais que tinha espaço, com boas condições de moradia. Que era só um banheiro, era três camas pra seis.</p>,
	<br/>,
	<p className='tar'>Tudo jogado no chão.</p>,
	<br/>,
	<p>Era.</p>,
	<br/>,
	<p className='tar'><b>O presidente no Ministério chegou foi lá e disse</b> – <i>olha, tá vendo aquele pessoal que tá lá na casa? Se, amanhã de manhã oito horas da manhã eu vou passar lá. Se tiver alguém lá ainda, aí vocês vão ter que pagar o dobre do que vocês vão ter que pagar</i>. <b>Aí a OAS endoideceu dentro de Guarulhos atrás de hotel pra cinquenta e dois homens. Quase não acha. Teve que ficar era separado, não foi?</b></p>,
	<br/>,
	<p>Foi.</p>
];