import React from 'react';

export default [
	<p className='bold text-font-big text-uppercase'>Nas alturas</p>,
	<br/>,
	<p className='tar'>Na Argentina. Argentina foi o trabalho que eu trabalhei mais alto. Trabalhei num prédio lá de <span className='bold'>98 andares</span>. Bem no topão. Argentina, Paraguay, Bolivia. Já rodei tudo. </p>,
	<br/>,
	<p>Eu tive no Maranhão. No maranhão eu trabalhava <span className='bold'>60 metros de altura</span>. Na barragem. Na barragem do estreito no Maranhão. </p>,
	<p className='tar'>Tô ligado. Eu trabalhei lá também. </p>,
	<p>Barragem de água, geradora de energia.</p>, 
	<br/>,
	<p className='tar'>Lá não dá tanto medo porque não treme, não se joga. Mas em prédio quando tá construindo lá em cima é perdido. Aí o cabra construindo quando dá um ventinho aí você sente fazendo RÁ RÁ. Chega faz assim ó. E o cabra olhando pra baixo lá vendo as pessoas lá em baixo, sabe aquelas formiguinhas bem miudinhas. Dá nem pra ver direito. </p>,
	<br/>,
	<p className='tar'>Eu trabalhava num <span className='bold'>dez andar</span> lá em Santos. No décimo andar. Quando nós tava de lá de cima de vez em quando eu ficava olhando ó... assim meio afastado pra não cair tábua né. Que lá era perigoso. Lá eu tava...não podia ficar assim embaixo lá. Que se caísse uma tábua de lá de cima era o fim. Tinha que ficar uns dez metros, uns dez metros afastado. Aí de vez em quando, quando eu olhava assim pra cima eu sentia ele.</p>,
	<br/>,
	<p className='bold tac'>.</p>,
	<br/>,
	<br/>,
	<p>B. O ferro tava solto, não caltearam, não amarraram.</p>,
	<br/>,
	<p>C. É ferro 32 né? De barragem?</p>,
	<br/>,
	<p>B. É, o fininho.</p>,
	<br/>,
	<p>M. Aí bateu em você quebrou o pé?</p>,
	<br/>,
	<p>N. Quebrou. Apaguei na hora.</p>,
	<br/>,
	<p>A. O cabra só trabalha que nem macaco. <span className='bold'>Pendurado</span>.</p>,
	<br/>,
	<p>C. É amarrado.</p>,
	<br/>,
	<p>M. Mas falaram que tem morte sim. Que é frequente. </p>,
	<br/>,
	<p>C. Tem. Sim.</p>,
	<br/>,
	<p>B. Em barragem é. </p>,
	<br/>,
	<p>C. Em barragem é.</p>,
	<br/>,
	<p>A. Em barragem é. Porque barragem os cara só trabalha de <span className='bold'>50 metros</span> a cima.</p>,
	<br/>,
	<p>B. É. Pendurado.</p>,
	<br/>,
	<p>A. É amarrando o ferro e subindo em cima. Amarrando o ferro e subindo em cima. </p>,
	<br/>,
	<p>C. Aí toda a barra que amarra, aqui, aí já sobe daquela que você tá em cima para aquela que foi amarrada. Vai subindo, passando o cinto e amarrando aquelas barras de ferro. Ali é muito perigoso.</p>,
	<br/>,
	<p>B. Mas é porque muitos caras... aprende uma coisa: você nunca, quando você tá subindo você nunca amarra... em ferro você bota deitado assim ó. Você tem que amarrar no que tá em pé. Porque se ele descer... você pode até cair, agora só se sair desmanchando tudo. Porque não tem condições. Agora se você amarrar aqui e o ferro se soltar, você desce junto com o ferro e já era.</p>,
	<br/>,
	<p>A. Porque aquele ele tem que tá tudinho até em baixo pro cabra cair.</p>,
	<br/>,
	<p>B. Sempre no vertical. Tem que amarrar sempre no que tá em pé.</p>,
	<br/>,
	<p>C. Eu nunca trabalhei em barragem não. Eu. Não foi falta de oportunidade não, foi falta de coragem mesmo. Bagaceira. Ali no Xingó mesmo morreu muita gente ali. Armador. </p>
];