import React from 'react';

export default [
	<p className='bold text-font-big text-uppercase'>É para não perder calado.</p>,
	<br/>,
	<p>Aí ela disse  – <span className='italic'>preciso de um menino que saiba ler o desenho, um encarregado e pode trazer mais um sete armador, oito.</span> Aí montei uma equipezinha só parceiros. Só família. Aí levei ele, meu pai, levei o irmão dela, que é meu cunhado, levei ela, minha esposa. Peguemos mais uns colegas, chamei pra lá, deu tudo certo. Fichemos. Quase dois meses de obra. Filézinho, tudo. Consegui um barraco ali naquele no Ângelo. Na favela no Ângelo. </p>,
	<br/>,
	<p className='tar'>­Jardim Ângela.</p>,
	<br/>,
	<p>Perto do Capão ali. Oxi fiquei doido pra ir nuns funk ali ó. Pra ir lá naquele show de rap muito massa dos Racionais, que eu sou fã dos cara. Eles são do Capão Redondo, Mano Brown. Os caras tudo ali. Eu tava lá no tempo que um policial embaçou com ele lá no meio da rua e ele mandou lá a mão. Massa demais. Policial capotou lá. Quando eles levaram o homem pra delegacia só bateu o ficho e contou dois e o advogado tirou o moleque. E foi embora. Foi demais. </p>,
	<p>Sim, aí como eu ia contar a história.. aí beleza, nós tamo lá trabalhando de boa isso já ia dar dois mês, já fazia quase dois mês. Aí apresenta uma senhora. Legalzinha ela. Mas mais uma vez deu um B.Ozinho. Quando foi, pagou o primeiro pagamento mais ou menos normal, quando chegou no segundo... lá é região de produção também. Quando chegou no segundo... teve um desvio de oitenta e dois tubulões. Tubulões seu pai sabe muito, engenheiro. Fundação. A média de doze a catorze metros de fundura, estaca. Faz a ferragem, joga lá dentro e concreta né. Mais oitenta e seis tubulões com cento e trinta e seis quilos cada um. Nós no peso, ganhando no peso.. oitenta e seis tubulão, cento e trinta e seis quilos cada um, nós dá cinquenta centavos o quilo. Isso pra dez, resumindo, dava duzentos e quarenta e seis real de diferença pra pagar. Mas como... é pouco. Mas duzentos e quarenta e seis pra oito cara. Os moleque tudinho quebraram, não chegaram junto de mim. O cabra ...... mas não podia ter condições não, tá faltando dinheiro aqui. – <span className='italic'>Calma aí eu vou conversar com ela.</span> Beleza. Aí ligeirinho ela, liguei pra ela – não, vamos refazer as contsa. Não importa. E mandou um ninja, que esse pessoal tanto gera fé, admirável o engenheiro, viu: vestido todo mala chegou, presença o moleque, todo cheio de paletó, ban ban ban. Óclicnho! Todo másculo, boyzinho mesmo. Cabelinho todo lambidinho. – <span className='italic'>Vamo pra cá, você é Josenildo?</span> Digo <span className='italic'>sou, então... – Beleza, vamos fazer nossas contas e tal</span>, todo falado, digo é, igual a um ninja. Depois chegou lá, nós subiu, pegou um note book aqui, pegou um note book abriu, e pá, pegou lá o carregadorzinho todo todo eu disse ó, <span className='italic'>ninja da febre</span>. E eu só ligado nele. E ele papapapapapa. Tudo que nós fez. </p>,
	<br/>,
	<p className='tar'>Doidinho pra enrolar ele. </p>,
	<br/>,
	<p>Por último... bem rápido. Agora isso bem rápido mesmo. Mas eu também que não sou muito não sou muito besta, ligado aqui dele. Anotou lá as placa, os bloco, tudo perfeito. Tudo certo. Quando chegou aí, tubulões de seis metro, de ferro dezesseis: seis tubulões. Eu digo <span className='italic'>como é? Volta aí. Como é? – Seis tubulões</span>. Digo aí,  <span className='italic'>agora aí a casa caiu. Nós fez noventa e quatro tubulão, rapaz</span>. E é aí onde é que tá o erro, onde é que tá o dinheiro da gente?  <span className='italic'>Vamo corrigir esse negócio aí...</span></p>,
	<br/>,
	<p className='tar'>Quando ele faz isso, tem problema. Cada vez que faz isso, dá problema.</p>,
	<br/>,
	<p>Aí – <span className='italic'>Mas você tem certeza não?</span> Mas aí quando ele, mas olha bem qual é o esquema. Pra ele, tava certo, mas no fundo no fundo quando eu comecei a me ligar, o mestre de obras tava envolvido no esquema. Os oitenta e quatro tubulão já tinha sido pago pra outra turma que tinha saído e não fez o serviço. Sobrou pra nossas costas. </p>,
	<br/>,
	<p className='tar'>– Mas só pra entender, você recebe pelo serviço que você faz. Aí por exemplo, se você coloca tubulão você recebe por.... não é o preço do tubulão que você tá falando. É o preço do serviço para por eles?</p>,
	<br/>,
	<p>É assim moça que funciona: Nós tem salário x em carteira e gato terceirizado é a mania que eles tem agora. Principalmente nessa região todinha. E produção. Quer dizer, o serviço sai rápido, a gente joga muito duro, se mata pra fazer, mas atrás disso aí tem todo um esquema que eles não quer pagar direito. Que seria: empresa grande.. você não se mata tanto, você trabalha normalzinho, mas é pra pagar hora extra. Mas esses gato de hoje, que chama setor terceirizado, eles quer pagar por produção. Aí que pega, mas sabendo que vai dar B.O. Diz que pega, mas eles só quer pagar pela metade do preço. </p>,
	<br/>,
	<p className='tar'>Eles falam que paga mas não paga não.</p>,
	<br/>,
	<p>Não paga, não quer pagar nem a metade da produção. </p>,
	<br/>,
	<p className='tar'>Na hora de entrar eles falam que paga tudo depois que os menino fazem não quer mais pagar. </p>,
	<br/>,
	<p>Aí vamos lá e vem cá vamos lá e vem cá</p>,
	<br/>,
	<p className='tar'>eles falam que se adoecer tem que trabalhar doente, não pode perder dia.</p>,
	<br/>,
	<p>É, quando a febre.... pai, pai, se lembra pai daquele mestre de obras, o apelido dele que era um apelido de um bicho do mato? Que era aquele véinho baixinho..</p>,
	<br/>,
	<p className='tar'>era o baixinho</p>,
	<br/>,
	<p>Bonézinho, um.... assim</p>,
	<br/>,
	<p className='tar'>era era ele teve um apelidozinho.</p>,
	<br/>,
	<p>Aí ele todo falante ligeirinho lá com seu notebook de boa aí – <span className='italic'>Você tem certeza que você fez noventa e quatro tubulões?</span> Aí eu digo <span className='italic'>tenho certeza absoluta, meu véio</span>. Ele disse ­– <span className='italic'>cadê o mestre? Vamos chamar ele. Vamos chamar ele</span>. O mestre fazia as anotação das ferramentas. Quando o mestre responsável contou ­–  que era um corredor do escritório, lá mesmo era onde a gente se vestia, tomava banho final do dia pra ir pra casa, tudo certinho ­–  o cara já vinha, o rosto do coroa já havia mudado. </p>,
	<br/>,
	<p className='tar'>Porque ele já sabia.</p>,
	<br/>,
	<p>Quando a fé, lá vem ele... cabeça baixa, tirou o capacete coçando a cabeça, aí falou com ele, aí o ligeirinho – <span className='italic'>ei, o menino tá falando aqui que foi noventa e seis tubulão. Como é que tu só passou seis pra mim? – Não, não....não sei o quê</span>. Inventou um monte de conversa – <span className='italic'>é porque nós pensava que tava pra fazer ainda, mas na conta do mês passado já tinha entrado, por isso que nós não queria que não entrasse novamente. – Não, mas se os meninos fizeram agora eles que receber</span>. Eu digo <span className='italic'>não só quer receber, agora você olha no pátio, o que fica estocado, se tem algum lá</span>. Tava tudinho enterrado e concretado. Isso não existe. Aí beleza, até aí tudo bem. Você acredita, resumindo, no decorrer de uma hora e meia esse dinheiro caiu na conta. Mas foi cair na conta e o meu celular tocando. – <span className='italic'>Ô Josenildo</span>. Eu digo <span className='italic'>oi. – Eu tô precisando que você venha aqui no meu escritório conversar</span>. Aí eu me liguei que a casa caiu. </p>,
	<br/>,
	<p className='tar'>Tudinho pra ir lá. Eu digo <span className='italic'>pronto, agora todo mundo embora</span>. </p>,
	<br/>,
	<p>Cheguei na turma todinha e digo <span className='italic'>olha, primeiro barraco pra não aparecer tudo fedendo no escritório</span>. Da mulher, eu falei <span className='italic'>troca essa roupa, toma um banho, pega suas carteirinhas que eu já conheço isso aí. Esse filme aí eu já assisti mais de trinta vez</span>. É só descer no escritório.</p>,
	<br/>,
	<p className='tar'>– O que acontece?</p>,
	<br/>,
	<p className='tar'>Manda embora.</p>,
	<br/>,
	<p>Manda embora na hora! Você não pode reclamar</p>,
	<br/>,
	<p className='tar'>essas coisas assim não pode reclamar</p>,
	<br/>,
	<p>lutando pelos seus direitos, sabendo que tu tá sendo roubado</p>,
	<br/>,
	<p className='tar'>mesmo que ela sem pagar, mas tem que ficar calado.</p>,
	<br/>,
	<p>Se nós fica calado, pelo menos aquela segunda terceira laje teria sido a gente que teria feito.</p>,
	<br/>,
	<p className='tar'>É pra perder calado.</p>,
	<br/>,
	<p>Se a gente não tivesse reclamado taria lá de pé. </p>,
	<br/>,
	<p className='tar'>Óia, se a gente não tivesse reclamado isso até hoje a gente tava lá trabalhando. Até hoje!</p>,
	<br/>,
	<p className='tar'>Agora sendo que todo mês sendo roubado.</p>
];